# Запуск
# docker-compose up -d                         запустите проект в фоновом режиме
# docker-compose exec gitlab-runner /bin/bash  Подключимся к контейнеру с gitlab-runner
# ./run_tests
# docker-compose stop                          Остановить контейнеры, запущенные в фоновом режиме
# docker-compose down                          не просто останавливает все запущенные контейнеры, но и удаляет их
# docker compose config                        отображения конфигурации, используемой Docker Compose для запуска реального проекта, + ошибки подробно

version: '3.5'
volumes:
  gitlab-config-vol:
    name: gitlab-config-vol    # чтобы использовал это имя, а не свое придумал, т.к. я уже в это положил данные
  gitlab-log-vol:
    name: gitlab-log-vol
  gitlab-data-vol:
    name: gitlab-data-vol
  gitlab-runner-config:
    name: gitlab-runner-config
networks:
  gitlab-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

services:

#  docker-nginx:
#    image: nginx
#    ports:
#      - '8094:80'
#    volumes:
#      - ./:/usr/share/nginx/html/

  gitlab:
    image: gitlab/gitlab-ce:latest
#    restart: always
    container_name: gitlab
    hostname: gitlab

    volumes:
      - gitlab-config-vol:/etc/gitlab
      - gitlab-log-vol:/var/log/gitlab
      - gitlab-data-vol:/var/opt/gitlab
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=database
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
    ports:
      - "443:443"
      - "80:80"
      - "22:22"
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest

    container_name: gitlab-runner
    hostname: gitlab-runner
    extra_hosts:   # добавить сопоставление имен хостов. Использует те же значения, что и параметр клиента docker --add-host.
      - "gitlab:172.25.0.3"
#      - gitlab:172.25.0.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
#    ports:
#      - "8095:80"
#    environment:
#      - PMA_HOST=docker-mariadb
    networks:
      - gitlab-network

